### ISSUE TITLE
Verifications for beginning, and completing iteration of a traversable / generator.

### ISSUE THREAD

**Issue by jmalloc** [eloquent/phony#102]
Possible syntax:
```php
$stub = Phony::stub()->does(function () { yield; });
$stub->never()->started();
```

**Comment by ezzatron** [comment]
I don't really like `started()`, too generic. Let's see if we can find a better name.

**Comment by ezzatron** [comment]
Also, the flip side of this is probably something like `consumed()` - verifying that a traversable was completely consumed via iteration.
