### ISSUE TITLE
Add support for methods that return references.

### ISSUE THREAD

**Issue by jmalloc** [eloquent/phony#105]
http://php.net/manual/en/language.references.return.php

**Comment by ezzatron** [comment]
@jmalloc Apparently generators can yield by reference too. Do you think that has any bearing here?

**Comment by ezzatron** [comment]
As discussed, to really support this would require lots of compromises, such as the use of `eval()` in mocked methods, and changing every spy's / stub's invoke method signature to always return by reference.

Given that we never use return by reference, I think that we should do just enough to prevent PHP from complaining. That is, make sure that methods have the same signature, including return-by-reference, and possibly to make mocked return-by-reference methods assign their result before returning.
