### ISSUE TITLE
Partial mock does not forward to trait implementation if method exists in interface.

### ISSUE THREAD

**Issue by jmalloc** [eloquent/phony#112]
When creating a partial mock using an array of types (an interface and trait), a method implementation provided by the trait will not be used if the interface contains a method of the same name.

The order of types in the array does not matter, and the problem does not affect classes, only traits.

```php
interface Interface_
{
    public function method();
}

trait Trait_
{
    public function method()
    {
        return '<result>';
    }
}

$mock = \Eloquent\Phony\Phony::partialMock([Interface_::class, Trait_::class]);

assert('<result>' === $mock->mock()->method());
```

**Comment by ezzatron** [comment]
At a guess, this might be the mock generator considering the methods 'uncallable'. Have a look for `uncallableMethodNames` if you want to give it a try.

Fucking traits.
