### ISSUE TITLE
Objects with __invoke method can not be used in custom methods

### ISSUE THREAD

**Issue by jmalloc** [eloquent/phony#113]
Not something I need, but still a bug IMO:

```php
$callable = new class {
    public function __invoke() {}
};

Phony::mock(
    null,
    ['method' => $callable]
);
```

Probably just needs some logic to construct a Reflector from `[$value, '__invoke']`, as the failure is:

```
TypeError: ReflectionFunction::__construct() expects parameter 1 to be string, object given
```

**Comment by ezzatron** [comment]
Just a heads up, I think I already do something like this elsewhere in Phony. I'll have a poke around and maybe the code can be recycled.

**Comment by ezzatron** [comment]
Yep, see [`InvocableInspector::callbackReflector()`](https://github.com/eloquent/phony/blob/develop/src/Invocation/InvocableInspector.php#L60).
