### ISSUE TITLE
Nullable parameters with type-hints are not directly supported

### ISSUE THREAD

**Issue by jmalloc** [eloquent/phony#114]
The method below has a parameter with that is nullable, followed by a non-optional parameter. It's an unfortunate consequence of using the default value of null to indicate a nullable parameter (rather than [something like this](https://wiki.php.net/rfc/nullable_types) that this is perfectly valid and sometimes necessary code.

```php
class Class_
{
    public function method(SomeClass $nullable = null, $notOptional) {}
}

$m = \Eloquent\Phony\Phony::mock(Class_::class);
$m->mock()->method(null, '<any>');
```

This code fails like so:

```
Uncaught TypeError: Argument 1 passed to PhonyMock__0::method() must be an
instance of SomeClass, null given, called in test.php on line 17 and defined in
MockFactory.php(146) : eval()'d code:5
```

I suspect the mock generation code is using the "number of required parameters" from the function reflector to determine whether or not a parameter has a default value, rather than checking each parameter individually, possibly as an optimisation.

**Comment by ezzatron** [comment]
Perhaps. It might also be in the function signature inspector somewhere.
