### ISSUE TITLE
Extend `GeneratorAnswerBuilderInterface` from `InvocableInterface`

### ISSUE THREAD

**Issue by jmalloc** [eloquent/phony#145]
How would you feel about making `InvocableInterface` available on generator answer builders, such that:

```php
$fn = Phony::stub()->generates();
$fn();
```

Is equivalent to:

```php
$fn = Phony::stub()->generates()->returns();
$fn();
```

**Comment by jmalloc** [comment]
I suppose if we went down this route, it's tempting to make other features usually on the stub available on this answer builder, which would be confusing as all hell.

**Comment by ezzatron** [comment]
Not keen to implement this at this stage.
