### ISSUE TITLE
Ability to check if any "on-destruct" warnings have occurred.

### ISSUE THREAD

**Issue by jmalloc** [eloquent/phony#178]
As far as I know the only such error is the 'unused stub criteria' warning.

I'd like to be able to fail CI builds when any such warning occurs. Perhaps the facade could gain some methods to start/end capturing such events. In which case they would not be printed to the terminal, but rather captured in an array. Much like `ob_get_clean()`, reading the events would clear the list.

You could then check for any such events at the end of each test/suite/build - whatever is appropriate. In my specific use case I'd probably use peridot's event system to check at the end of each test.

**Comment by jmalloc** [comment]
Given #179, I'm happy to close this. The common case will be easier to spot, and less likely in the first place.

**Comment by jmalloc** [comment]
And then I immediately had second thoughts.  I'd still prefer to be able to fail the build.

**Comment by ezzatron** [comment]
As discussed, this is no longer really relevant.
