### ISSUE TITLE
Add public/protected/private method mocking strategies & caveats

### ISSUE THREAD

**Issue by ezzatron** [eloquent/phony#186]
The documentation currently has nothing to say about `public`, `protected`, and `private` methods. Even just a little section would help for those searching for caveats.

To recap:
- *Phony* overrides `public` and `protected` methods.
- *Phony* does not change the access level of mocked methods. I.e. `public` stays `public`, and `protected` stays `protected`.
- Calling a `protected` method still requires bypassing the access modifier. That means either:
    - Using `ReflectionMethod::setAccessible()`
    - Using [Liberator](https://github.com/eloquent/liberator)
- Stubbing and verification "just work" for `protected` methods.
- I don't know of any way to mock `private` methods, and it's probably a bad idea in the first place.

**Comment by ezzatron** [comment]
@shadowhand FYI

**Comment by shadowhand** [comment]
Thanks @ezzatron. I thought I would have to do something special with non-public methods, but Phony made it too simple. Would be good to have the documentation reflect this, as people coming from (eg) phpunit will expect to jump through hoops that aren't there.
