### ISSUE TITLE
Call count verification

### ISSUE THREAD

**Issue by enumag** [eloquent/phony#194]
Is there a better way to verify call count?

```
self::assertSame(1, $mockHandle->method->callCount());
```

I'd prefer something like this:

```
$mockHandle->method->calledTimes(1);
```

Or did I miss some better API to do this?

**Comment by ezzatron** [comment]
The feature you're looking for is referred to as [Cardinality](http://eloquent-software.com/phony/latest/#verifying-cardinality-with-spies). Basically, just call `once()` before `called()`:

```php
$mockHandle->method->once()->called();
```

There are plenty of other cardinality "modifiers" also, documented in the link above.

**Comment by enumag** [comment]
Thanks!
