### ISSUE TITLE
PHP 7.1 features

### ISSUE THREAD

**Issue by ezzatron** [eloquent/phony#195]
New features that need to be evaluated for use with *Phony*:

- [x] Nullable types (`?string`) in argument lists and return types - affects code generation, stub default return values
- [x] `void` return type - affects code generation, stub default return values
- [x] Class constant visibility - affects mock builders
- [x] `iterable` pseudo-type - affects code generation, possibly other areas
- [x] "Disallow the ASCII delete control character in identifiers" - might mean a change to some regexes?
- [x] "call_user_func() fails on calls to functions with reference arguments" - probably not an issue, so long as `call_user_func_array()` still works

More details at http://php.net/manual/en/migration71.php

**Comment by jmalloc** [comment]
I think the success of [this job](https://travis-ci.org/eloquent/phony/jobs/158431659) means that the `call_user_func()` item can be crossed off.
