### ISSUE TITLE
Error when running under HHVM

### ISSUE THREAD

**Issue by shadowhand** [eloquent/phony#203]
When running a test that uses Phony with HHVM, this error appears:

```
Fatal error: Syntax only allowed in Hack files (<?hh) or with -v Eval.EnableHipHopSyntax=true in vendor/eloquent/phony/src/Reflection/FeatureDetector.php(533) : eval()'d code on line 1
```

Job source https://travis-ci.org/thephpleague/oauth2-client/jobs/173009708

I find this particularly odd, since I have used Phony in another project that tests on HHVM without issues. Any idea what the cause is?

**Comment by shadowhand** [comment]
This was working in version 0.13.4 and is broken in 0.13.5+, since the introduction of PHP 7.1 support in 6bf897cb2215ff209ba5e2794c55faaa63d6b4b4.

**Comment by ezzatron** [comment]
Apologies, but there's a regression of this bug in 0.14.5. It will be fixed soon in a patch release.
