### ISSUE TITLE
Seeking suggestions for exporter format improvements

### ISSUE THREAD

**Issue by ezzatron** [eloquent/phony#210]
@jmalloc @koden-km @darianbr @parkertr I'm wondering what you guys think of these exporter format changes I'm thinking of making, and whether you have any other suggestions.

I've got a feature in the works to add support for limiting output by breadth. Meaning that if an array or object has more than a fixed number of members, the output will be truncated. If I were to follow the current syntax, it would look something like this (with a breadth of 2):

```php
[1, 2, 3, 4]; // '#0[1, 2, :2]'
(object) ['a' => 'a', 'b' => 'b', 'c' => 'c', 'd' => 'd']; // '#0{a: "a", b: "b", :2}'
```

With `:2` indicating that there are 2 members that are truncated. This is similar to when depth limiting kicks in, like so (with a depth of 0):

```php
[1, 2, 3, 4]; // '#0[:4]'
(object) ['a' => 'a', 'b' => 'b', 'c' => 'c', 'd' => 'd']; // '#0{:4}'
```

First question is; if such a feature were implemented, what would you consider a reasonable default for breadth?

Secondly, hindsight is making me question why I chose `:` as the character for this. What do you think about `+` instead:

```
#0[1, 2, +2]
#0[+4]

#0{a: "a", b: "b", +2}
#0{+4}
```

It seems more intuitive to me. The other obvious option is to use `...`, but it's a bit less succinct:

```
#0[1, 2, ...+2]
#0[...+4]

#0{a: "a", b: "b", ...+2}
#0{...+4}
```

**Comment by ezzatron** [comment]
FYI, there are docs on all the current behaviour at http://eloquent-software.com/phony/latest/#the-exporter

**Comment by ezzatron** [comment]
Also, possible reason I decided not to use `+` was because it's also used in the word-diff output:

    [-chameleon-]{+capybara+}

**Comment by jmalloc** [comment]
`Repr` uses `+` in similar way ... Delimiting the "breadth indicator", something like `[1, 2, <+2>]` could help avoid ambiguities with the diff syntax, but it'd still be a line full of symbols.

**Comment by koden-km** [comment]
The dots make sense to me, `...4`. But if you need single character what about `#4`, `^4` or `~4`?

**Comment by ezzatron** [comment]
@jmalloc Yeah. Makes me think that the goal of retaining standard word diff syntax is not really that important in the face of how confusing this output can be. I was hoping to keep it that way so that tools like colordiff could still be used, but I think that's pretty edge case.

@koden-km I don't want to just use `...4`, because to me, that means "some stuff, then integer 4", like when people truncate lists:

    1, 2, 3, 4, ...100

`#` is no good either, it's already used for object and array identifiers like `#0{}` and `#0[]`. Out of the ones you suggested, `~` is probably the best option, but I still don't know if I prefer it over `+`.

**Comment by darianbr** [comment]
`[1, 2, 3, 4]; // '#0[1, 2, <2 more>]'` would be my preference.

`#0["bonobo", "[-chameleon-]{+capybara+}", "dugong", <4 more>]`

`[1, 2[-]-]{+, <4 more>+}]`

**Comment by ezzatron** [comment]
@darianbr talked about the `more` idea in person. I don't mind it, but it could actually make for longer output in some circumstances:

    #0[#1[<1 more>], #2[<1 more>], #3[<1 more>], #4[<1 more>], #5[<1 more>], #6[<1 more>]]

So far, @koden-km's `~` seems like the best option. It handles that case as well as the current code:

    #0[#1[~1], #2[~1], #3[~1], #4[~1], #5[~1], #6[~1]]

It also has some prior art usage that is relevant here. It has been used for [abbreviation](https://en.wikipedia.org/wiki/Tilde#Abbreviation) in text, and of course, for the same reason with Windows filenames 😂 

    c:\progra~1\

**Comment by jmalloc** [comment]
Please provide a phony/depict cheat sheet ;)

**Comment by ezzatron** [comment]
@jmalloc Not sure if srs, but what would you want on it beyond what's listed [here](http://eloquent-software.com/phony/latest/#the-export-format)?

**Comment by jmalloc** [comment]
Not rly srs
