### ISSUE TITLE
Abstract functions in partial mocks do not use default return values.

### ISSUE THREAD

**Issue by jmalloc** [eloquent/phony#212]
No such issue occurs with full mocks. And (probably unsurprisingly) use `forwards()` does not work either.

Source:
```php
abstract class C
{
    abstract function F() : int;
}

$h = Phony::partialMock(C::class);

var_dump($m->get()->F());
```

Expected output:
```
0
```

Actual Output:
```
Return value of PhonyMock_C_0::F() must be of the type integer, null returned
```

**Comment by ezzatron** [comment]
@jmalloc If you get a chance, could you give `dev-abstract-return-type` a go?

**Comment by jmalloc** [comment]
That means I have to remember where the hell this even happened ;)

**Comment by jmalloc** [comment]
It works, though as I mentioned it turned out I couldn't use the default value in the particular test where I came across this.
