### ISSUE TITLE
PHPUnit 6 support

### ISSUE THREAD

**Issue by nesl247** [eloquent/phony#213]
PHPUnit 6 namespaced everything, and thus phony is currently broken.

**Comment by ezzatron** [comment]
Thanks for the heads up.

**Comment by ezzatron** [comment]
I've made a branch for this called `phpunit6`. You can try it out by using `dev-phpunit6` as your Composer version constraint for `eloquent/phony`.

There are some difficult issues surrounding Phony's support for older PHP versions, and PHPUnit's dropping of support for said versions. The CI setup is getting pretty crazy at this point, and I definitely want to drop support for some PHP versions going forward, but there's a fair bit of work there before I can address the problem "properly". Hopefully the branch gets you what you need for now.

**Comment by enumag** [comment]
@ezzatron I think you should add phpunit <6 to conflicts in composer.json. Then you can get rid of ugly ifs like [this one](https://github.com/eloquent/phony/commit/7c66aab4c720b674bd21db24a09c445720a56858#diff-e072ec2a225e4bc3a544fd5009759d0bR42).

**Comment by ezzatron** [comment]
Phony still supports PHPUnit <6 for the time being. I will probably drop support for it at the same time as I drop support for PHP <7, which is coming.

No argument about the current solution being hacky, just wanted to get something out there quickly.

**Comment by ezzatron** [comment]
This has now been released. For PHPUnit 6 support, please change your Phony requirement to `eloquent/phony-phpunit` at `^2`. Do not use `^1`, which is for PHPUnit 4/5.
