### ISSUE TITLE
Warning that each() is deprecated when using "nightly" builds

### ISSUE THREAD

**Issue by shadowhand** [eloquent/phony#217]
https://travis-ci.org/RoundingWellOS/schematic/jobs/249681211#L236-L242

Matcher verification generates this warning:

> The `each()` function is deprecated. This message will be suppressed on further calls

I believe this will be an `E_DEPRECATED` in PHP 7.2+

**Comment by ezzatron** [comment]
Man, that's really annoying. Well, thanks for the report. I'll have to re-work the matcher/argument verification.

I also have to apologise that I didn't catch this sooner. My CI builds are currently ignoring deprecations, and I need to address that.

**Comment by shadowhand** [comment]
👍

**Comment by ezzatron** [comment]
Released in [1.0.1](https://github.com/eloquent/phony/releases/1.0.1).
