### ISSUE TITLE
Possible future issue with global function mocking.

### ISSUE THREAD

**Issue by jmalloc** [eloquent/phony#234]
[This RFC](https://wiki.php.net/rfc/fallback-to-root-scope-deprecation) proposes that 'fallback to root scope' be ~~removed~~ deprecated in PHP 7.3.

**Comment by ezzatron** [comment]
Cheers, will have to keep an eye on that. Thankfully, there's already a section discussing alternatives in the documentation: http://eloquent-software.com/phony/latest/#alternatives-for-stubbing-global-functions

**Comment by ezzatron** [comment]
Well, 7.3 was released today, and this RFC is still "under discussion". No changes needed yet.

**Comment by ezzatron** [comment]
Closing until this rears its head again.
