### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by ezzatron** [eloquent/phony#239]

**Comment by jmalloc** [comment]
Doesn't look like there will be too much to worry about? https://ayesh.me/Upgrade-PHP-7.3#pcre2 could cause trouble, but it doesn't seem that there's anything there that wouldn't be caught by tests.

**Comment by ezzatron** [comment]
Yeah, there are no major code changes. The nightly build was failing, but it's fixed now. I don't think there's anything that actually requires new features.

**Comment by enumag** [comment]
Just found out that phony doesn't work in PHP 7.3 but is [fixed](https://github.com/eloquent/phony/commit/6b90a60ccb785791b7283095378505d8df625a5b) in master. Any chance to get a release?

**Comment by ezzatron** [comment]
There's a branch alias on master, so you should already be able to use the `^4` constraint right now to get PHP 7.3 support.

**Comment by ezzatron** [comment]
@enumag Apologies, for some reason I forgot that the PHP 7.3 fixes would not be a new major release. In any case, I just published [3.1.0](https://github.com/eloquent/phony/releases/3.1.0) with PHP 7.3 support.
