### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by danepowell** [eloquent/phony#257]
Running this library under PHP 8.2 results in a number of warnings:

> PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead

https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated

**Comment by ezzatron** [comment]
Thanks for the heads up. I can't commit to any particular timeline for PHP 8 support unfortunately, but it's on my list of things to tackle!

**Comment by ezzatron** [comment]
Just a heads up that this particular issue is fixed on `main`, but unfortunately full PHP 8.1 / 8.2 support will still require tackling a bunch of harder issues (see #265 for a summary). Thanks for the help with #258 👍
