### ISSUE TITLE
Constructor is not called on mocked trait.

### ISSUE THREAD

**Issue by jmalloc** [eloquent/phony#61]
```php
trait MyTrait
{
    public function __construct(array $x) {}
}

Phony::mock(MyTrait::class, [[1, 2, 3]]);
```

Error:
```
Eloquent\Asplode\Error\ErrorException: Argument 1 passed to PhonyMock_MyTrait_0::__construct() must be of the type array, none given in <filename> : eval()'d code on line 12
```

**Comment by ezzatron** [comment]
Traits with constructors can now be mocked. Rules:

- If any non-trait class has a constructor, it takes precedence.
- If there are multiple traits being mocked, and multiple trait constructors, the last trait will take precedence. This matches the precedence used when resolving other trait method conflicts.
- Private trait constructors *can* be mocked if closure binding is supported.
