### ISSUE TITLE
Banish the evil wizard Sebastian

### ISSUE THREAD

**Issue by ezzatron** [eloquent/phony#70]
The new exporter has weakened him. All we need to break his curse once and for all is a simple deep equals comparator. Hear my call, knight @jmalloc, and aid me in this noble task!

Deep within the labyrinth of Phony™, in a crypt known only as "[EqualToMatcher](https://github.com/eloquent/phony/blob/develop/src/Matcher/EqualToMatcher.php)", lies a scrawl of cursed runes:

```php
        $comparator = $this->comparatorFactory
            ->getComparatorFor($this->value, $value);

        try {
            $comparator->assertEquals($this->value, $value);
        } catch (ComparisonFailure $e) {
            return false;
        }

        return true;
```

A brave hero need only make it to the crypt, and replace the runes with a spell of his own design, and the evil wizard's bond will be broken. Will you be the hero this land needs?

**Comment by ezzatron** [comment]
@jmalloc jam pls

**Comment by jmalloc** [comment]
How do I compared web?
