### ISSUE TITLE
Promise stubbing and verification.

### ISSUE THREAD

**Issue by jmalloc** [eloquent/phony#78]
Based on our discussion the other day, here's some quick and dirty ideas. 

## Promise Results

Easily configure stubs to reject/resolve with a promise. Can be interleaved with regular returns/throws:

```php
$stub = Phony::stub();

$stub
    ->returns(1)
    ->throws($e1)
    ->resolvesTo(2)
    ->rejectsWith($e2);
```

The above would be equivalent to:

```php
$stub
    ->returns(1)
    ->throws($1)
    ->returns(React\Promise\resolve(2))
    ->throws(React\Promise\reject($e));
```

## Cancellation

Promises can be cancelled, it would be great to be able to verify that the consumer of the promise did/didn't cancel it:

```php
$stub->cancelled()
$stub->neverCancelled()
```

## Notifications

Promises also support [notifications](https://github.com/reactphp/promise#deferrednotify), essentially an event handler for a specific promise. It'd be handy to trigger those BEFORE a resolve/reject, but in the same call to the stub.

Maybe something like:

```php
$stub->notifies($n1, $n2)->resolvesTo(null)
```

I don't know if that's possible, but in that example `notifies` wouldn't specify the behavior for a specific call, but rather configures the values to sent to the promise via `$deferred->notify()` before resolving with null.

**Comment by ezzatron** [comment]
All of that *should* technically be possible. Look at `Stub` implementation for the relevant code.

The idea behind `notifies` (something that happens as a part of an 'answer') already exists for other things, and could probably be implemented by using `callsWith` (see the implementation of `setsArgument`).

We need to make sure we leave room in the interface for generators, too (see #11).

**Comment by jmalloc** [comment]
I was actually just digging in `setsArgument` for unrelated reasons... that part should be straight forward.  I'll have a crack at a PR if it gets frustrating mocking this stuff for recoil/amqp.

**Comment by ezzatron** [comment]
We would probably also want the verification side of resolve and reject. I.e. `resolvedTo()` and `rejectedWith()`.

**Comment by ezzatron** [comment]
And perhaps `notified()`.

**Comment by ezzatron** [comment]
And `cancels()`.

**Comment by ezzatron** [comment]
I think also to avoid performance overhead, Promise spies would have to be turned on by something similar to `setUsePromiseSpies()`.

**Comment by jmalloc** [comment]
FWIW, promise "notifications" never made it into the promises/A+ spec (or something to that effect), I found them difficult to use in any implementation-agnostic way, and they're being removed from the React promise implementation.

**Comment by ezzatron** [comment]
As discussed, I probably won't implement anything special for Promise stubbing. Basically because:

    ->resolvesTo(2)

Is barely better than:

    ->resolvesTo(Promise::resolve(2))

And would require an internal promise implementation, or a dependency on some existing promise library.

**Comment by ezzatron** [comment]
As discussed, I'm not going to implement this feature, at least for now. There's no way within any existing promise standard to verify that a promise has already resolved/rejected, which makes the utility of this feature limited.
